# aws compute - dev-vm
# Generated by scripts/cloud.init.sh on 2026-08-18
#
# A personal development VM built from the shared Packer image, reachable only
# through SSM Session Manager.
#
# The single requirement that shapes every resource below: no SSH port is exposed
# to the internet. That is not implemented by narrowing an inbound rule to a home
# IP address -- it is implemented by there being no inbound rule and no public IP
# at all. Session Manager works entirely from the instance outward: the SSM agent
# opens a WebSocket to the regional endpoint, and the console or CLI meets it
# there. So:
#
#   - the instance sits in a private subnet with associate_public_ip_address false
#   - its security group has zero ingress rules and no key pair is attached
#   - egress through a NAT gateway is the only path in or out
#
# The consequence worth knowing before you rely on it: a broken SSM agent is a
# lockout, because there is no second door. EC2 Serial Console is the break-glass
# path -- see the recovery section of the README.

locals {
  name = "${var.project_name}-dev-vm-${var.environment}"

  # Required tags per docs/standards/TAGGING_STANDARDS.md
  common_tags = merge(
    {
      Environment = var.environment
      Project     = var.project_name
      ManagedBy   = "terraform"
      Component   = "compute"
      Owner       = var.owner
      CostCenter  = var.cost_center
    },
    var.tags
  )

  # var.ami_id wins when set. See the variable's description: a pinned id is what
  # keeps `terraform plan` from quietly proposing to replace the VM after someone
  # rebuilds the image.
  ami_id = var.ami_id != "" ? var.ami_id : data.aws_ami.dev_vm.id

  # The VM is placed in the first AZ and stays there, because its home directory
  # is an EBS volume and EBS volumes are zonal. Moving the instance to another AZ
  # means snapshotting and restoring the volume, not editing an index.
  subnet_id         = module.vpc.private_subnet_ids[0]
  availability_zone = module.vpc.availability_zones[0]

  # Ubuntu names its release "24.04"; the Packer image name flattens it to 2404.
  ami_name_filter = "${var.ami_name_prefix}-ubuntu${replace(var.ubuntu_release, ".", "")}-${var.architecture}-*"
}

module "vpc" {
  source = "../../../shared/modules/vpc"

  project_name = "${var.project_name}-dev-vm"
  environment  = var.environment
  vpc_cidr     = var.vpc_cidr
  az_count     = var.az_count

  # The box has to reach apt, GitHub and ghcr, so interface endpoints alone are
  # not enough and a NAT gateway is not optional here.
  enable_nat_gateway = true
  single_nat_gateway = var.single_nat_gateway

  tags = local.common_tags
}

# The image Packer produced. Filtering on the image_version tag rather than only
# on "most recent" is the pin: two builds of 0.1.0 still differ, so pass
# var.ami_id from shared/packer/manifest.json when a stable plan matters. Without
# a pin, a fresh build changes this id and Terraform will propose replacing the
# instance -- which it can do safely, since the home directory is on a volume it
# is not allowed to delete, but not silently.
data "aws_ami" "dev_vm" {
  owners      = var.ami_owners
  most_recent = true

  filter {
    name   = "name"
    values = [local.ami_name_filter]
  }

  filter {
    name   = "tag:component"
    values = ["dev-vm"]
  }

  filter {
    name   = "tag:image_version"
    values = [var.ami_image_version]
  }

  filter {
    name   = "state"
    values = ["available"]
  }
}

# Outbound only. There is deliberately no `ingress` block in this resource: the
# absence is the security control, so do not add a port 22 rule "just for
# debugging" -- Session Manager already gives you a shell, and adding one is the
# exact thing this design exists to prevent.
resource "aws_security_group" "dev_vm" {
  name        = "${local.name}-sg"
  description = "dev-vm: egress only. SSM Session Manager needs no inbound rule."
  vpc_id      = module.vpc.vpc_id

  egress {
    description = "SSM endpoints, apt, GitHub, container registries, and DNS to the VPC resolver."
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = var.egress_cidr_blocks
  }

  tags = merge(local.common_tags, {
    Name = "${local.name}-sg"
  })

  # The SG is referenced by a running instance, so it must be created before the
  # old one is destroyed on any change that forces replacement.
  lifecycle {
    create_before_destroy = true
  }
}

# The home directory. Kept out of the instance's own lifecycle on purpose: this
# is the only resource in the stack that holds work, so `terraform destroy` must
# not be able to take it. prevent_destroy turns a destroy into a loud error
# rather than a lost afternoon; see the README for how to intentionally retire it.
resource "aws_ebs_volume" "home" {
  availability_zone = local.availability_zone
  size              = var.data_volume_size
  type              = "gp3"
  encrypted         = true
  kms_key_id        = var.kms_key_arn != "" ? var.kms_key_arn : null

  tags = merge(local.common_tags, {
    Name    = "${local.name}-home"
    Role    = "persistent-home"
    FsLabel = "devhome"
  })

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_instance" "dev_vm" {
  ami           = local.ami_id
  instance_type = var.instance_type
  subnet_id     = local.subnet_id

  vpc_security_group_ids = [aws_security_group.dev_vm.id]
  iam_instance_profile   = aws_iam_instance_profile.dev_vm.name

  # The two lines that make this VM unreachable from the internet. No public IP,
  # and no key_name: there is no SSH key to leak because there is no SSH.
  associate_public_ip_address = false

  # IMDSv2 only. IMDSv1's plain GET is what turns an SSRF in anything running on
  # this box into a credential theft; requiring a token and a hop limit of 1 stops
  # both the proxied request and the containerised one.
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }

  root_block_device {
    volume_size           = var.root_volume_size
    volume_type           = "gp3"
    encrypted             = true
    kms_key_id            = var.kms_key_arn != "" ? var.kms_key_arn : null
    delete_on_termination = true

    tags = merge(local.common_tags, {
      Name = "${local.name}-root"
    })
  }

  ebs_optimized = true

  # Stop rather than terminate on an in-guest `poweroff`, which is exactly what
  # shared/bootstrap/idle-shutdown.sh issues. Terminating there would destroy the
  # instance every time the box went idle.
  instance_initiated_shutdown_behavior = "stop"

  user_data = local.user_data

  # Rewriting the boot config must not replace the machine. cloud-init applies
  # write_files on every boot, so a changed user_data lands on the next stop/start
  # -- which the idle timer performs nightly anyway.
  user_data_replace_on_change = false

  # The AMI id is the one attribute that should force replacement, and that is
  # intentional: the image is the unit of change for this box. Everything worth
  # keeping across a replacement lives on the data volume.
  tags = merge(local.common_tags, {
    Name = local.name
    Role = "dev-vm"
  })

  # Fail the apply rather than hand back a VM that violates the two properties
  # this whole design exists to hold. A postcondition catches the case a plan
  # review would miss: an account-level or subnet-level default that assigns a
  # public IP anyway.
  lifecycle {
    postcondition {
      condition     = self.public_ip == ""
      error_message = "The dev VM was assigned a public IP. It must be reachable only through SSM Session Manager; check the subnet's map_public_ip_on_launch."
    }

    postcondition {
      condition     = self.metadata_options[0].http_tokens == "required"
      error_message = "Instance metadata is reachable without a session token (IMDSv1). Any SSRF on this box would then be a credential leak."
    }
  }
}

# Attached at /dev/sdf; the Nitro hypervisor presents it to the guest as
# /dev/nvme1n1, which is what var.data_disk_device tells seed-home.sh to expect.
resource "aws_volume_attachment" "home" {
  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.home.id
  instance_id = aws_instance.dev_vm.id

  # Detaching a mounted ext4 filesystem is how you corrupt it. Let AWS stop the
  # instance first, and do not let Terraform force the detach.
  stop_instance_before_detaching = true
  force_detach                   = false
}
