# azure compute - dev-vm
# Generated by scripts/cloud.init.sh on 2026-08-18

locals {
  name = "${var.project_name}-dev-vm-${var.environment}"

  # Required tags per docs/standards/TAGGING_STANDARDS.md
  common_tags = merge(
    {
      Environment = var.environment
      Project     = var.project_name
      ManagedBy   = "terraform"
      Component   = "compute"
      Owner       = var.owner
      CostCenter  = var.cost_center
    },
    var.tags
  )
}

# TODO: declare the dev-vm resources here.
